<?php
if ( !defined('ABSPATH')) exit; // Exit if accessed directly
/**
 *  Specific page output template
 */
/*! ** DO NOT EDIT THIS FILE! It will be overwritten when the theme is updated! ** */

	$sb_layout = weaverx_page_lead( '404', true );

	weaverx_sb_precontent('404');

		// and next the content area.
?>
		<article id="post-0" class="post error404 not-found">
			<?php
				$msg = apply_filters('weaverx_404_title', __('Sorry, no such page.','weaver-xtreme'));
				weaverx_page_title( $msg );

			if (!weaverx_getopt('_hide_not_found_search')) { ?>
				<div class="entry-content clearfix">
					<p><?php echo __( 'It seems we can&rsquo;t find what you&rsquo;re looking for. Perhaps searching, or one of the links below, can help.','weaver-xtreme'); ?>
					</p>

				<?php
				get_search_form();
				echo "<p></p>\n";
				the_widget( 'WP_Widget_Recent_Posts', array( 'number' => 10 ), array( 'widget_id' => '404' ) );
				?>
					<div class="widget">
						<h2 class="widgettitle"><?php echo __( 'Most Used Categories','weaver-xtreme'); ?></h2>
						<ul>
							<?php wp_list_categories( array( 'orderby' => 'count', 'order' => 'DESC', 'show_count' => 1, 'title_li' => '', 'number' => 10 ) ); ?>
						</ul>
					</div>

				<?php

				/* translators: %1$s: smilie */
				$archive_content = '<p>' . sprintf( __( 'Try looking in the monthly archives. %1$s','weaver-xtreme'), convert_smilies( ':)' ) ) . '</p>';
				the_widget( 'WP_Widget_Archives', array('count' => 0 , 'dropdown' => 1 ), array( 'after_title' => '</h2>'.$archive_content ) );
				the_widget( 'WP_Widget_Tag_Cloud' );
				?>

				</div><!-- .entry-content -->
			<?php
			}      	// don't show not found message
			?>
		</article><!-- #post-0 -->

		<?php
	weaverx_page_tail( '404', $sb_layout );    // end of page wrap
?>
