<?php
if ( !defined('ABSPATH')) exit; // Exit if accessed directly
/**
 * Template Name: Blank
 *
 */
/*! ** DO NOT EDIT THIS FILE! It will be overwritten when the theme is updated! ** */

	$sb_layout = weaverx_page_lead( 'page-blank' );

	// and next the content area.

	weaverx_sb_precontent('page-blank');

	// generate page content

	while ( have_posts() ) {
		weaverx_post_count_clear();

		the_post();

		get_template_part( 'templates/content', 'blank' );

		comments_template( '', true );
	}


	weaverx_sb_postcontent('page-blank');

	weaverx_page_tail( 'page-blank', $sb_layout );    // end of page wrap
?>
