<?php
if ( !defined('ABSPATH')) exit; // Exit if accessed directly
/**
 *   Template Name: Sitemap
 */
/*! ** DO NOT EDIT THIS FILE! It will be overwritten when the theme is updated! ** */

	$sb_layout = weaverx_page_lead( 'sitemap' );

	// and next the content area.
	weaverx_sb_precontent('sitemap');

	// generate page content

	while ( have_posts() ) {
		weaverx_post_count_clear(); the_post();

		get_template_part( 'templates/content', 'sitemap' );

		comments_template( '', true );
	}


	weaverx_sb_postcontent('sitemap');

	weaverx_page_tail( 'sitemap', $sb_layout );    // end of page wrap
?>
